### ISSUE TITLE
Sending with a Mailable doesn't return the number of emails sent

### ISSUE THREAD

**Issue by balweb** [andrewdyer/slim3-mailer#3]
When the sendMessage from the Mailable class is used nothing is returned. 
If the return value of $mailer->sendMessage() in Mailable::sendMessage is returned, the number of emails sent will be returned to the user. By this can be checked if emails are sent.

**Comment by andrewdyer** [comment]
I have updated `Mailable::sendMessage` to return the the number of emails sent. Thanks for the feedback.
