### ISSUE TITLE
Cannot use with PHP 7.0?

### ISSUE THREAD

**Issue by GaryReckard** [andrewdyer/slim3-mailer#5]
Hi there. I am trying to include your library with my project, but I am using PHP 7.0.15, and your package says it requires PHP 7.1.14. 

What PHP features does your project use that aren't available in PHP 7.0? Do you have any plans to make this compatible with older versions? Thanks!

**Comment by andrewdyer** [comment]
Downgraded to version 7. It was likely a mistake on my part. Swiftmailer is dependent on PHP 7.
